package model;
// Generated 08-30-2020 05:04:32 PM by Hibernate Tools 4.3.1



/**
 * Tbempleado generated by hbm2java
 */
public class Tbempleado  implements java.io.Serializable {


     private int idEmpleado;
     private Tbdepartamento tbdepartamento;
     private Tbmunicipio tbmunicipio;
     private Tbpais tbpais;
     private String nombres;
     private String apellidos;
     private String direccion;
     private String codigoArea;
     private String telefono;

    public Tbempleado() {
    }

	
    public Tbempleado(int idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public Tbempleado(int idEmpleado, Tbdepartamento tbdepartamento, Tbmunicipio tbmunicipio, Tbpais tbpais, String nombres, String apellidos, String direccion, String codigoArea, String telefono) {
       this.idEmpleado = idEmpleado;
       this.tbdepartamento = tbdepartamento;
       this.tbmunicipio = tbmunicipio;
       this.tbpais = tbpais;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.direccion = direccion;
       this.codigoArea = codigoArea;
       this.telefono = telefono;
    }
   
    public int getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(int idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public Tbdepartamento getTbdepartamento() {
        return this.tbdepartamento;
    }
    
    public void setTbdepartamento(Tbdepartamento tbdepartamento) {
        this.tbdepartamento = tbdepartamento;
    }
    public Tbmunicipio getTbmunicipio() {
        return this.tbmunicipio;
    }
    
    public void setTbmunicipio(Tbmunicipio tbmunicipio) {
        this.tbmunicipio = tbmunicipio;
    }
    public Tbpais getTbpais() {
        return this.tbpais;
    }
    
    public void setTbpais(Tbpais tbpais) {
        this.tbpais = tbpais;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getCodigoArea() {
        return this.codigoArea;
    }
    
    public void setCodigoArea(String codigoArea) {
        this.codigoArea = codigoArea;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }




}


