package model;
// Generated 08-30-2020 05:04:32 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tbpais generated by hbm2java
 */
public class Tbpais  implements java.io.Serializable {


     private int idPais;
     private String nombrePais;
     private Set<Tbdepartamento> tbdepartamentos = new HashSet<Tbdepartamento>(0);
     private Set<Tbempleado> tbempleados = new HashSet<Tbempleado>(0);

    public Tbpais() {
    }

	
    public Tbpais(int idPais, String nombrePais) {
        this.idPais = idPais;
        this.nombrePais = nombrePais;
    }
    public Tbpais(int idPais, String nombrePais, Set<Tbdepartamento> tbdepartamentos, Set<Tbempleado> tbempleados) {
       this.idPais = idPais;
       this.nombrePais = nombrePais;
       this.tbdepartamentos = tbdepartamentos;
       this.tbempleados = tbempleados;
    }
   
    public int getIdPais() {
        return this.idPais;
    }
    
    public void setIdPais(int idPais) {
        this.idPais = idPais;
    }
    public String getNombrePais() {
        return this.nombrePais;
    }
    
    public void setNombrePais(String nombrePais) {
        this.nombrePais = nombrePais;
    }
    public Set<Tbdepartamento> getTbdepartamentos() {
        return this.tbdepartamentos;
    }
    
    public void setTbdepartamentos(Set<Tbdepartamento> tbdepartamentos) {
        this.tbdepartamentos = tbdepartamentos;
    }
    public Set<Tbempleado> getTbempleados() {
        return this.tbempleados;
    }
    
    public void setTbempleados(Set<Tbempleado> tbempleados) {
        this.tbempleados = tbempleados;
    }




}


